;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Event.Montage.MeleeAttack",NewTagName="Event.Montage.Attack.Melee")
+GameplayTagRedirects=(OldTagName="GameplayCue.ArcaneShard",NewTagName="GameplayCue.ArcaneShards")
+GameplayTagRedirects=(OldTagName="Cooldown.Arcane.ArcaneAra",NewTagName="Cooldown.Arcane.ArcaneArea")
+GameplayTagList=(Tag="Abilities.Lightning.ChainedLightning",DevComment="")
+GameplayTagList=(Tag="Abilities.Lightning.ConeBeam",DevComment="")
+GameplayTagList=(Tag="Abilities.Lightning.SpawnElectroSphere.StopMovement",DevComment="")
+GameplayTagList=(Tag="Abilities.Lightning.SpinningBeam",DevComment="")
+GameplayTagList=(Tag="Abilities.Lightning.SpinningBeam.Cone",DevComment="")
+GameplayTagList=(Tag="Abilities.Lightning.SpinningBeam.Fixed",DevComment="")
+GameplayTagList=(Tag="Abilities.Passive.ListenForEvent",DevComment="")
+GameplayTagList=(Tag="AbilityUpgrades.FireBolt.IncreaseNum",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.BlockedByTags",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.CantAffordCost",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.IsDead",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.MissingTags",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.Networking",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.OnCooldown",DevComment="")
+GameplayTagList=(Tag="Attributes.Secondary",DevComment="2차 속성")
+GameplayTagList=(Tag="CombatSocket.Spine",DevComment="")
+GameplayTagList=(Tag="Cooldown.Arcane.ArcaneArea",DevComment="")
+GameplayTagList=(Tag="Cooldown.Arcane.ArcaneOrbit",DevComment="")
+GameplayTagList=(Tag="Cooldown.Arcane.ArcaneShards",DevComment="")
+GameplayTagList=(Tag="Cooldown.Boss.Arcane.ArcaneShards",DevComment="")
+GameplayTagList=(Tag="Cooldown.Boss.Fire.FireBolt",DevComment="")
+GameplayTagList=(Tag="Cooldown.Boss.Lightning.SpinningBeam",DevComment="")
+GameplayTagList=(Tag="Cooldown.Fire.FireBlast",DevComment="")
+GameplayTagList=(Tag="Cooldown.Fire.FireNado",DevComment="")
+GameplayTagList=(Tag="Cooldown.Lightning.ChainedLightning",DevComment="")
+GameplayTagList=(Tag="Cooldown.Lightning.ConeBeam",DevComment="")
+GameplayTagList=(Tag="Cooldown.Lightning.Electrocute",DevComment="")
+GameplayTagList=(Tag="Cooldown.Lightning.SpawnElectroSphere",DevComment="")
+GameplayTagList=(Tag="Cooldown.Lightning.Teleport",DevComment="")
+GameplayTagList=(Tag="Cost.Mana.Teleport",DevComment="")
+GameplayTagList=(Tag="Data.MagicAttackPower",DevComment="")
+GameplayTagList=(Tag="Data.MovementSpeed",DevComment="")
+GameplayTagList=(Tag="Data.MovementSpeed.Slow",DevComment="")
+GameplayTagList=(Tag="Effects.Invulnerable",DevComment="")
+GameplayTagList=(Tag="Effects.Item.Stat",DevComment="")
+GameplayTagList=(Tag="Event.Montage.ArcaneShards",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Boss.RoarEnd",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Boss.RoarStart",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Electrocute",DevComment="")
+GameplayTagList=(Tag="Event.Montage.FireBolt",DevComment="파이어볼트 발사")
+GameplayTagList=(Tag="Event.Montage.SpawnElectroSphere",DevComment="")
+GameplayTagList=(Tag="Event.RangeIndicator",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Arcane.Impact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Arcane.Spawn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ArcaneOrbit.MissileExplosion",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ArcaneShards",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Cast.MindControl",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Cast.Teleport",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ChainedLightning",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ElectroSphere",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ElectroSphere.Destroy",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ElectroSphere.Looping",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ElectroSphere.Spawn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Firebolt",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Firebolt.Looping",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FireboltImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FireNado.Destroy",DevComment="")
+GameplayTagList=(Tag="GameplayCue.FireNado.Spawn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.MeleeImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Message.WaitForExecute",DevComment="")
+GameplayTagList=(Tag="GameplayCue.MindControl",DevComment="")
+GameplayTagList=(Tag="GameplayCue.RangeIndicator.Box",DevComment="")
+GameplayTagList=(Tag="GameplayCue.RangeIndicator.Circle",DevComment="")
+GameplayTagList=(Tag="GameplayCue.RangeIndicator.Star",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShockBurst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShockImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShockLoop",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShockLoop.SpinningBeam",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Slingshot.Impact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Summon",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Teleport",DevComment="")
+GameplayTagList=(Tag="Init.Revive.HalfHPMP",DevComment="")
+GameplayTagList=(Tag="InputTag.MouseWheel",DevComment="")
+GameplayTagList=(Tag="Message.GamePausedBy",DevComment="")
+GameplayTagList=(Tag="Message.GameSaved",DevComment="")
+GameplayTagList=(Tag="Message.GetAttributePoints",DevComment="")
+GameplayTagList=(Tag="Message.GetItem",DevComment="")
+GameplayTagList=(Tag="Message.GetSpellPoints",DevComment="")
+GameplayTagList=(Tag="Message.HealthCrystal",DevComment="")
+GameplayTagList=(Tag="Message.HealthPotion",DevComment="")
+GameplayTagList=(Tag="Message.InventoryFull",DevComment="")
+GameplayTagList=(Tag="Message.LevelUp",DevComment="")
+GameplayTagList=(Tag="Message.ManaCrystal",DevComment="")
+GameplayTagList=(Tag="Message.ManaPotion",DevComment="")
+GameplayTagList=(Tag="Message.NotEnoughInferiorSpellLevel",DevComment="")
+GameplayTagList=(Tag="Message.NotEnoughLevel",DevComment="")
+GameplayTagList=(Tag="Message.NotEnoughSpellPoints",DevComment="")
+GameplayTagList=(Tag="Message.Tutorial.NextDialogue",DevComment="")
+GameplayTagList=(Tag="Message.WaitForExecute",DevComment="")
+GameplayTagList=(Tag="Mission.Dungeon5",DevComment="")
+GameplayTagList=(Tag="Mission.Objective.Damage",DevComment="")
+GameplayTagList=(Tag="Mission.Objective.Kill.Boss",DevComment="")
+GameplayTagList=(Tag="Mission.Objective.Trigger",DevComment="")
+GameplayTagList=(Tag="Mission.Scarecrow",DevComment="")
+GameplayTagList=(Tag="Mission.Scarecrow.Kill",DevComment="")
+GameplayTagList=(Tag="Mission.Shaman.Kill",DevComment="")
+GameplayTagList=(Tag="Montage.Teleport",DevComment="")
+GameplayTagList=(Tag="Player.Block.InputBlocked",DevComment="")
+GameplayTagList=(Tag="Sound",DevComment="")
+GameplayTagList=(Tag="Sound.Background.Ambient",DevComment="")
+GameplayTagList=(Tag="Sound.Background.Boss.Shaman.Defeated",DevComment="")
+GameplayTagList=(Tag="Sound.Background.Boss.Shaman.Phase1",DevComment="")
+GameplayTagList=(Tag="Sound.Background.Boss.Shaman.Phase2",DevComment="")
+GameplayTagList=(Tag="State.AIReady",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="Upgrades.Arcane.ArcaneArea.MindControl",DevComment="")
+GameplayTagList=(Tag="Upgrades.Arcane.ArcaneArea.TakeDamage",DevComment="")
+GameplayTagList=(Tag="Upgrades.Arcane.ArcaneOrbit.FFE",DevComment="")
+GameplayTagList=(Tag="Upgrades.Arcane.ArcaneShards.Multiple",DevComment="")
+GameplayTagList=(Tag="Upgrades.Fire.FireBolt.SpeedUp",DevComment="")
+GameplayTagList=(Tag="Upgrades.Fire.FireNado.IncreaseLifeSpan",DevComment="")
+GameplayTagList=(Tag="Upgrades.Lightning.ChainedLightning.AdditionalTarget",DevComment="")
+GameplayTagList=(Tag="Upgrades.Lightning.ChainedLightning.IncreaseChainRadius",DevComment="")
+GameplayTagList=(Tag="Upgrades.Lightning.ChainedLightning.NoReduction",DevComment="")
+GameplayTagList=(Tag="Upgrades.Lightning.SpawnElectroSphere.StopMovement",DevComment="")

